version: 2
jobs:
  build:

    working_directory: ~/user_managemant_firstinstance

    docker:
      - image: circleci/openjdk:8-jdk-stretch


    steps:

      - checkout

      - restore_cache:
          key: user_managemant_firstinstance-{{ checksum "pom.xml" }}

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: user_managemant_firstinstance-{{ checksum "pom.xml" }}

      - run: mvn clean package

      - store_test_results:
          path: target/surefire-reports

      - store_artifacts:
          path: target/demo-0.0.1-SNAPSHOT.jar