version: 2
jobs:
  build:

    working_directory: ~/user_managemant_firstinstance

    docker:
      - image: circleci/openjdk:8-jdk-stretch

    steps:

      - checkout

      - restore_cache:
          key: user_managemant_firstinstance-{{ checksum "pom.xml" }}

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: user_managemant_firstinstance-{{ checksum "pom.xml" }}

      - run: mvn clean package -Dunit-tests.skip=true
      - store_artifacts:
          path: target/demo-0.0.1-SNAPSHOT.jar

  Unit Test:
    steps:
       - run : mvn test
       - store_test_results:
         path: target/surefire-reports



