version: 2
jobs:
  build:

    working_directory: ~/user_managemant_firstinstance

    docker:
      - image: circleci/openjdk:8-jdk-stretch

    steps:

      - checkout

      - restore_cache:
          key: user_managemant_firstinstance-{{ checksum "pom.xml" }}

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: user_managemant_firstinstance-{{ checksum "pom.xml" }}

      - run: mvn clean package -Dunit-tests.skip=true
      - store_artifacts:
          path: target/demo-0.0.1-SNAPSHOT.jar

  Unit-Test:
    orbs:
      maven: circleci/maven@1.0.0
    working_directory: ~/user_managemant_firstinstance
    docker:
      - image: circleci/openjdk:8-jdk-stretch
    steps:

       - run : mvn test
           key: user_managemant_firstinstance-{{ checksum "pom.xml" }}
       - store_test_results:
           path: target/surefire-reports

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build
      - Unit-Test:
          requires:
            - build

